#!/bin/bash
# ======================================================================
# Make Calendar Todo Template
# Quick and dirty script to make a calendar todo template for organizing 
# tasks and events.
# Author: Camilo Tejeiro
# ======================================================================

if [ -e $1 ]; then # check to avoid overwriting existing files.
    printf "%s\n" "File $1 already exists"
elif [ -z $2 ]; then # check if second parametter is empty.
    printf "%s\n" 'you need to specify a valid year.'
else
    # initialize our local vars for our script.
    current_date="$2-01-01"
    end_date="$2-12-31"
    print_date=$(date -d "$current_date" +%a\ %m/%d/%Y)

    # Print greeting message.
    printf "%s\n" "* Creating $1 Template for year $2 * "
    printf "%s\n" "Starting Date: $current_date"
    printf "%s\n" "End Date: $end_date"

    # Print the header lines.
    printf "%s\n" '**************************' > $1
    printf "%s\n" '# Personal Calendar Todo #' >> $1
    printf "%s\n" '--------------------------' >> $1
    printf "%s\n" "##         $2         ##" >> $1
    printf "%s\n\n" '**************************' >> $1

    # Print first date.
    printf "%s\n" '--------------------' >> $1
    printf "%s\n" "## $print_date ##" >> $1
    printf "%s\n\n\n" '--------------------' >> $1

    # Iterate and print every day in the current year.
    while [ "$current_date" != "$end_date" ]; do
        current_date=$(date -d "$current_date 1 days" +%Y-%m-%d)
        print_date=$(date -d "$current_date" +%a\ %m/%d/%Y)

        printf "%s\n" '--------------------' >> $1
        printf "%s\n" "## $print_date ##" >> $1
        printf "%s\n\n\n" '--------------------' >> $1
    done
fi
